# Generated by Django 5.0.2 on 2025-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
