# Generated by Django 5.0.2 on 2025-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(default='Ahmad', max_length=50),
        ),
    ]
