# Generated by Django 5.0.2 on 2025-01-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_email_alter_patient_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(max_length=50),
        ),
    ]
