# Generated by Django 5.0.2 on 2025-01-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(default='Qais', max_length=50),
        ),
    ]
